"resources"
{
"maps/ff_hold.lua" "file"
"maps/ff_hold.txt" "file"
"materials/ff_hold/com_shield003a_w.vmt" "file"
"materials/ff_hold/decal_signroute007ab.vmt" "file"
"materials/ff_hold/ff_fieldstone_blue_yellow.vmt" "file"
"materials/ff_hold/ff_fieldstone_green_blue.vmt" "file"
"materials/ff_hold/ff_fieldstone_green_red.vmt" "file"
"materials/ff_hold/ff_fieldstone_red_yellow.vmt" "file"
"materials/ff_hold/ff_hold_grate02.vmt" "file"
"materials/ff_hold/comshieldwall_close_w.vtf" "file"
"materials/ff_hold/decal_signroute007ab.vtf" "file"
"materials/ff_hold/ff_fieldstone_blue_yellow.vtf" "file"
"materials/ff_hold/ff_fieldstone_green_blue.vtf" "file"
"materials/ff_hold/ff_fieldstone_green_red.vtf" "file"
"materials/ff_hold/ff_fieldstone_red_yellow.vtf" "file"
"materials/ff_hold/flag_neutral_test.vtf" "file"
"materials/vgui/loadingscreens/ff_hold.vtf" "file"
"materials/vgui/loadingscreens/ff_hold.vmt" "file"
"sound/ff_hold/blue-team-has-the-flag.wav" "file"
"sound/ff_hold/red-team-has-the-flag.wav" "file"
"sound/ff_hold/yellow-team-has-the-flag.wav" "file"
"sound/ff_hold/green-team-has-the-flag.wav" "file"
"sound/ff_hold/the-flag-has-returned.wav" "file"
}
