"resources"
{
"maps/ff_stowaway_b2.lua" "file"
"maps/ff_stowaway_b2.res" "file"
"maps/ff_stowaway_b2_soundscapes.txt" "file"
"materials/ff_stowaway/basetrim02.vmt" "file"
"materials/ff_stowaway/basetrim02.vtf" "file"
"materials/ff_stowaway/bz_e_14shipextwallbolted_01.vmt" "file"
"materials/ff_stowaway/bz_e_14shipextwallbolted_01.vtf" "file"
"materials/ff_stowaway/doortrim01.vmt" "file"
"materials/ff_stowaway/doortrim01.vtf" "file"
"materials/ff_stowaway/ff_roasted_yellowdecal.vmt" "file"
"materials/ff_stowaway/ff_roasted_yellowdecal.vtf" "file"
"materials/ff_stowaway/ff_roasted_yellowline.vmt" "file"
"materials/ff_stowaway/ff_roasted_yellowline.vtf" "file"
"materials/ff_stowaway/ff_stowaway_logo.vmt" "file"
"materials/ff_stowaway/ff_stowaway_logo.vtf" "file"
"materials/ff_stowaway/ff_stowaway_metal_red_lowsat.vmt" "file"
"materials/ff_stowaway/ff_stowaway_metal_red_lowsat.vtf" "file"
}
