"resources"
{
"materials/vgui/loadingscreens/ff_verdun_xmas.vmt" "file"
"materials/vgui/loadingscreens/ff_verdun_xmas.vtf" "file"
"models/models_kit/xmas/xmastree.dx80.vtx" "file"
"models/models_kit/xmas/xmastree.dx90.vtx" "file"
"models/models_kit/xmas/xmastree.mdl" "file"
"models/models_kit/xmas/xmastree.phy" "file"
"models/models_kit/xmas/xmastree.sw.vtx" "file"
"models/models_kit/xmas/xmastree.vvd" "file"
"models/models_kit/xmas/xmastree_mini.dx80.vtx" "file"
"models/models_kit/xmas/xmastree_mini.dx90.vtx" "file"
"models/models_kit/xmas/xmastree_mini.mdl" "file"
"models/models_kit/xmas/xmastree_mini.phy" "file"
"models/models_kit/xmas/xmastree_mini.sw.vtx" "file"
"models/models_kit/xmas/xmastree_mini.vvd" "file"
"materials/models/models_kit/xmas/xmastree_miscA.vmt" "file"
"materials/models/models_kit/xmas/xmastree_miscA.vtf" "file"
"materials/models/models_kit/xmas/xmastree_miscA_skin2.vmt" "file"
"materials/models/models_kit/xmas/xmastree_miscA_skin2.vtf" "file"
"materials/models/models_kit/xmas/xmastree_miscB.vmt" "file"
"materials/models/models_kit/xmas/xmastree_miscB.vtf" "file"
"materials/models/models_kit/xmas/xmastree_miscB_skin2.vmt" "file"
"materials/models/models_kit/xmas/xmastree_miscB_skin2.vtf" "file"
"materials/models/models_kit/xmas/xmastree_miscB_spec.vtf" "file"
"maps/ff_verdun_xmas.bsp" "file"
"maps/ff_verdun_xmas.txt" "file"
"maps/ff_verdun_xmas.lua" "file"
}
